export const supplierSeed = [
  {
    name: "Accra Device Hub",
    category: "Phones & laptops",
    contactEmail: "ops@accradevicehub.com",
    averageLeadDays: 3,
    reliabilityScore: 96,
    nextDelivery: "Mon 13:00",
    openOrders: 2,
    fillRate: 98,
    notes: "Consistent on flagship phones and laptop refresh cycles.",
  },
  {
    name: "BlueOrbit Logistics",
    category: "Laptops & chargers",
    contactEmail: "support@blueorbitlogistics.com",
    averageLeadDays: 6,
    reliabilityScore: 74,
    nextDelivery: "Delayed 2d",
    openOrders: 3,
    fillRate: 81,
    notes: "Two-day variance on chargers and entry-level laptops.",
  },
  {
    name: "VoltLine Ghana",
    category: "Accessories & peripherals",
    contactEmail: "sales@voltlinegh.com",
    averageLeadDays: 2,
    reliabilityScore: 91,
    nextDelivery: "Tomorrow",
    openOrders: 1,
    fillRate: 95,
    notes: "High confidence for accessories and peripherals.",
  },
] as const;

export const productSeed = [
  {
    sku: "TA-IP15-128",
    name: "iPhone 15 128GB",
    category: "Phones",
    supplierName: "Accra Device Hub",
    unitCost: 4800,
    unitPrice: 5900,
    onHand: 9,
    reorderPoint: 12,
    leadDays: 3,
    weeklyVelocity: 6.1,
    shelfZone: "A-01",
    status: "critical",
  },
  {
    sku: "TA-HP-ELB",
    name: "HP EliteBook 840",
    category: "Laptops",
    supplierName: "BlueOrbit Logistics",
    unitCost: 1500,
    unitPrice: 1900,
    onHand: 6,
    reorderPoint: 5,
    leadDays: 6,
    weeklyVelocity: 2.2,
    shelfZone: "B-03",
    status: "watch",
  },
  {
    sku: "TA-PB-20K",
    name: "Power Bank 20,000mAh",
    category: "Accessories",
    supplierName: "VoltLine Ghana",
    unitCost: 160,
    unitPrice: 270,
    onHand: 18,
    reorderPoint: 24,
    leadDays: 2,
    weeklyVelocity: 13.4,
    shelfZone: "C-02",
    status: "critical",
  },
  {
    sku: "TA-KB-MX",
    name: "Mechanical Keyboard MX",
    category: "Accessories",
    supplierName: "VoltLine Ghana",
    unitCost: 180,
    unitPrice: 320,
    onHand: 22,
    reorderPoint: 14,
    leadDays: 2,
    weeklyVelocity: 5.3,
    shelfZone: "C-05",
    status: "healthy",
  },
  {
    sku: "TA-CH-65W",
    name: "65W GaN Charger",
    category: "Accessories",
    supplierName: "BlueOrbit Logistics",
    unitCost: 90,
    unitPrice: 190,
    onHand: 14,
    reorderPoint: 18,
    leadDays: 6,
    weeklyVelocity: 9.6,
    shelfZone: "C-01",
    status: "watch",
  },
] as const;

export const salesSeed = [
  { soldAt: "2026-01-01", sku: "TA-IP15-128", quantity: 7, revenue: 41300, grossMargin: 0.238, channel: "retail", productCategory: "Phones" },
  { soldAt: "2026-01-01", sku: "TA-HP-ELB", quantity: 9, revenue: 46700, grossMargin: 0.184, channel: "retail", productCategory: "Laptops" },
  { soldAt: "2026-01-01", sku: "TA-PB-20K", quantity: 46, revenue: 12420, grossMargin: 0.289, channel: "online", productCategory: "Accessories" },
  { soldAt: "2026-01-01", sku: "TA-CH-65W", quantity: 50, revenue: 9500, grossMargin: 0.312, channel: "retail", productCategory: "Accessories" },
  { soldAt: "2026-01-01", sku: "SERV-JAN", quantity: 32, revenue: 16000, grossMargin: 0.42, channel: "service", productCategory: "Services" },
  { soldAt: "2026-02-01", sku: "TA-IP15-128", quantity: 8, revenue: 47200, grossMargin: 0.238, channel: "retail", productCategory: "Phones" },
  { soldAt: "2026-02-01", sku: "TA-HP-ELB", quantity: 9, revenue: 45300, grossMargin: 0.184, channel: "retail", productCategory: "Laptops" },
  { soldAt: "2026-02-01", sku: "TA-PB-20K", quantity: 52, revenue: 14040, grossMargin: 0.289, channel: "online", productCategory: "Accessories" },
  { soldAt: "2026-02-01", sku: "TA-CH-65W", quantity: 51, revenue: 9760, grossMargin: 0.312, channel: "retail", productCategory: "Accessories" },
  { soldAt: "2026-02-01", sku: "SERV-FEB", quantity: 37, revenue: 18500, grossMargin: 0.42, channel: "service", productCategory: "Services" },
  { soldAt: "2026-03-01", sku: "TA-IP15-128", quantity: 9, revenue: 53100, grossMargin: 0.238, channel: "retail", productCategory: "Phones" },
  { soldAt: "2026-03-01", sku: "TA-HP-ELB", quantity: 9, revenue: 43700, grossMargin: 0.184, channel: "retail", productCategory: "Laptops" },
  { soldAt: "2026-03-01", sku: "TA-PB-20K", quantity: 55, revenue: 14850, grossMargin: 0.289, channel: "online", productCategory: "Accessories" },
  { soldAt: "2026-03-01", sku: "TA-CH-65W", quantity: 54, revenue: 10250, grossMargin: 0.312, channel: "retail", productCategory: "Accessories" },
  { soldAt: "2026-03-01", sku: "SERV-MAR", quantity: 39, revenue: 19600, grossMargin: 0.42, channel: "service", productCategory: "Services" },
  { soldAt: "2026-04-01", sku: "TA-IP15-128", quantity: 10, revenue: 59000, grossMargin: 0.243, channel: "retail", productCategory: "Phones" },
  { soldAt: "2026-04-01", sku: "TA-HP-ELB", quantity: 10, revenue: 45700, grossMargin: 0.184, channel: "retail", productCategory: "Laptops" },
  { soldAt: "2026-04-01", sku: "TA-PB-20K", quantity: 60, revenue: 16200, grossMargin: 0.289, channel: "online", productCategory: "Accessories" },
  { soldAt: "2026-04-01", sku: "TA-CH-65W", quantity: 67, revenue: 12700, grossMargin: 0.312, channel: "retail", productCategory: "Accessories" },
  { soldAt: "2026-04-01", sku: "SERV-APR", quantity: 44, revenue: 22800, grossMargin: 0.42, channel: "service", productCategory: "Services" },
  { soldAt: "2026-05-01", sku: "TA-IP15-128", quantity: 11, revenue: 64900, grossMargin: 0.248, channel: "retail", productCategory: "Phones" },
  { soldAt: "2026-05-01", sku: "TA-HP-ELB", quantity: 11, revenue: 51300, grossMargin: 0.184, channel: "retail", productCategory: "Laptops" },
  { soldAt: "2026-05-01", sku: "TA-PB-20K", quantity: 63, revenue: 17010, grossMargin: 0.289, channel: "online", productCategory: "Accessories" },
  { soldAt: "2026-05-01", sku: "TA-CH-65W", quantity: 76, revenue: 14400, grossMargin: 0.312, channel: "retail", productCategory: "Accessories" },
  { soldAt: "2026-05-01", sku: "SERV-MAY", quantity: 47, revenue: 24000, grossMargin: 0.42, channel: "service", productCategory: "Services" },
  { soldAt: "2026-06-01", sku: "TA-IP15-128", quantity: 12, revenue: 70800, grossMargin: 0.243, channel: "retail", productCategory: "Phones" },
  { soldAt: "2026-06-01", sku: "TA-HP-ELB", quantity: 12, revenue: 52700, grossMargin: 0.184, channel: "retail", productCategory: "Laptops" },
  { soldAt: "2026-06-01", sku: "TA-PB-20K", quantity: 69, revenue: 18630, grossMargin: 0.289, channel: "online", productCategory: "Accessories" },
  { soldAt: "2026-06-01", sku: "TA-CH-65W", quantity: 85, revenue: 16170, grossMargin: 0.312, channel: "retail", productCategory: "Accessories" },
  { soldAt: "2026-06-01", sku: "SERV-JUN", quantity: 53, revenue: 25900, grossMargin: 0.42, channel: "service", productCategory: "Services" },
] as const;

export const forecastSeed = [
  { sku: "TA-IP15-128", weekStart: "W1", predictedUnits: 32, actualUnits: 28, confidence: 0.91, stockOutRisk: 0.64 },
  { sku: "TA-PB-20K", weekStart: "W1", predictedUnits: 24, actualUnits: 22, confidence: 0.92, stockOutRisk: 0.71 },
  { sku: "TA-HP-ELB", weekStart: "W1", predictedUnits: 12, actualUnits: 10, confidence: 0.89, stockOutRisk: 0.34 },
  { sku: "TA-IP15-128", weekStart: "W2", predictedUnits: 34, actualUnits: 30, confidence: 0.91, stockOutRisk: 0.66 },
  { sku: "TA-PB-20K", weekStart: "W2", predictedUnits: 25, actualUnits: 24, confidence: 0.92, stockOutRisk: 0.73 },
  { sku: "TA-HP-ELB", weekStart: "W2", predictedUnits: 11, actualUnits: 10, confidence: 0.88, stockOutRisk: 0.35 },
  { sku: "TA-IP15-128", weekStart: "W3", predictedUnits: 35, actualUnits: 31, confidence: 0.92, stockOutRisk: 0.68 },
  { sku: "TA-PB-20K", weekStart: "W3", predictedUnits: 24, actualUnits: 24, confidence: 0.93, stockOutRisk: 0.75 },
  { sku: "TA-HP-ELB", weekStart: "W3", predictedUnits: 12, actualUnits: 10, confidence: 0.88, stockOutRisk: 0.36 },
  { sku: "TA-IP15-128", weekStart: "W4", predictedUnits: 37, actualUnits: 33, confidence: 0.92, stockOutRisk: 0.7 },
  { sku: "TA-PB-20K", weekStart: "W4", predictedUnits: 26, actualUnits: 25, confidence: 0.93, stockOutRisk: 0.78 },
  { sku: "TA-HP-ELB", weekStart: "W4", predictedUnits: 13, actualUnits: 10, confidence: 0.88, stockOutRisk: 0.37 },
  { sku: "TA-IP15-128", weekStart: "W5", predictedUnits: 39, actualUnits: undefined, confidence: 0.93, stockOutRisk: 0.74 },
  { sku: "TA-PB-20K", weekStart: "W5", predictedUnits: 28, actualUnits: undefined, confidence: 0.94, stockOutRisk: 0.81 },
  { sku: "TA-HP-ELB", weekStart: "W5", predictedUnits: 13, actualUnits: undefined, confidence: 0.89, stockOutRisk: 0.38 },
  { sku: "TA-IP15-128", weekStart: "W6", predictedUnits: 41, actualUnits: undefined, confidence: 0.93, stockOutRisk: 0.76 },
  { sku: "TA-PB-20K", weekStart: "W6", predictedUnits: 29, actualUnits: undefined, confidence: 0.94, stockOutRisk: 0.83 },
  { sku: "TA-HP-ELB", weekStart: "W6", predictedUnits: 14, actualUnits: undefined, confidence: 0.89, stockOutRisk: 0.39 },
] as const;

export const alertSeed = [
  {
    title: "Stock-out window inside 3 days",
    detail: "Power banks and iPhone 15 units are likely to dip below safe cover before the next intake lands.",
    severity: "critical",
    kind: "stockout",
    sku: "TA-PB-20K",
    open: true,
    createdAt: "2026-06-20T08:00:00.000Z",
  },
  {
    title: "Supplier delay variance detected",
    detail: "BlueOrbit Logistics is running 32% slower than its baseline for charger deliveries.",
    severity: "watch",
    kind: "supplier",
    sku: "TA-CH-65W",
    open: true,
    createdAt: "2026-06-20T09:30:00.000Z",
  },
  {
    title: "Demand uplift opportunity",
    detail: "Accessory attach rate has moved from 1.6x to 1.9x on premium phone purchases.",
    severity: "info",
    kind: "opportunity",
    sku: "TA-IP15-128",
    open: true,
    createdAt: "2026-06-20T10:15:00.000Z",
  },
] as const;

export const recommendationSeed = [
  {
    title: "Increase charger safety stock",
    detail: "Raise reorder point from 18 to 24 units while supplier variance remains elevated.",
    impact: "Protects 2.1 weeks of demand",
  },
  {
    title: "Bundle flagship phones with power banks",
    detail: "Cross-sell promotion can lift accessory revenue without increasing device markdown pressure.",
    impact: "Projected +8.4% bundle margin",
  },
  {
    title: "Shift one open PO to Accra Device Hub",
    detail: "Split the delayed laptop replenishment across the more reliable distributor.",
    impact: "Cuts stock-out risk on entry laptops by 19%",
  },
] as const;
